name = "anastasia-labs/aiken-design-patterns"
version = "v1.9.0"
compiler = "v1.1.24"
plutus = "v3"
license = "MIT"
description = "Implementations of common design patterns for Cardano smart contracts"

[repository]
user = "anastasia-labs"
project = "aiken-design-patterns"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v4.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "keyan-m/aiken-scott-utils"
version = "v1.5.0"
source = "github"

[config]
